---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_tower:
      url: https://localhost
      admin_username: 'admin'
      admin_password: 'admin123'
      tower_cli_file: '~/.tower_cli.cfg'
      verify_ssl: 'false'
    ansible_debug_no_log: "{{ ansible_verbosity | bool }}"
    tower_verify_ssl: 'false'
    environment_type: tower_admin

  vars_files:
    - "environments/{{ environment_type }}.yml"

  pre_tasks:

    - name: merge new environemnt vars
      set_fact:
        ansible_tower: "{{ ansible_tower|default({})|combine(ansible_tower_overides) }}"

    - name: debug ansible_tower var
      debug:
        var: ansible_tower
        verbosity: 4

  roles:
    - role: lshake.tower-modules
    - role: lshake.create-organisations
    - role: lshake.create-credentials
    - role: lshake.create-projects
    - role: lshake.create-inventories
    - role: lshake.create-inventory-sources
    - role: lshake.create-job-templates
