---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "vars/configure_tower_defaults.yml"
    - "environments/{{ environment_type }}.yml"

  pre_tasks:

    - name: merge new environemnt vars
      set_fact:
        ansible_tower: "{{ ansible_tower|default({})|combine(ansible_tower_overides) }}"

    - name: debug ansible_tower var
      debug:
        var: ansible_tower
        verbosity: 4

  roles:
    - role: lshake.tower-modules
    - role: lshake.create-organisations
    - role: lshake.create-credentials
    - role: lshake.create-projects
    - role: lshake.create-inventories
    - role: lshake.create-inventory-sources
    - role: lshake.create-job-templates
    - role: lshake.create-teams
