---
# tasks file for lshake.create-inventory-sources

- name: include tasks for each inventory
  include_tasks: create_inventory_sources.yml
  loop: "{{ ansible_tower.organizations | subelements('inventories') }}"
  loop_control:
    loop_var: this_inventory
    label: "{{ this_inventory.0.name }} {{ this_inventory.1.name }}"
  no_log: "{{ ansible_debug_no_log | default('true') }}"
  when: this_inventory.1.sources is defined
