---
- name: create template "{{ this_template.name }}"
  tower_job_template:
    name: "{{ this_template.name }}"
    description: "{{ this_template.description | default(omit) }}"
    project: "{{ this_project.1.name }}"
    job_type: "{{ this_template.job_type | default('run') }}"
    playbook: "{{ this_template.playbook }}"
    inventory: "{{ this_template.inventory }}"
    credential: "{{ this_template.credential }}"
#     vault_credential: "{{ this_template.vault_credential | default(omit) }}"
    state: "{{ this_template.state | default('present') }}"
    tower_host: "{{ ansible_tower.url | default(omit) }}"
    tower_username: "{{ ansible_tower.tower_username | default(omit) }}"
    tower_password: "{{ ansible_tower.tower_password | default(omit) }}"
    tower_verify_ssl: "{{ ansible_tower.verify_ssl | default('true') }}"
    survey_enabled: "{{ this_template.survey_enabled | default(omit) }}"
    survey_spec: "{{ this_template.survey_spec | default({}) | to_json | default(omit) }}"
    skip_tags: "{{ this_template.skip_tags | default(omit)}}"
  no_log: "{{ ansible_debug_no_log | default('true') }}"
  register: new_job_template

- name: add patch data to the job template "{{ this_template.name }}"
  uri:
    url: "{{ ansible_tower.url | regex_replace('\\/$','')}}/api/v2/job_templates/{{ new_job_template.id }}/"
    user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    password: "{{ ansible_tower.admin_password }}"
    force_basic_auth: yes
    method: PATCH
    body: "{{ this_template.patch | to_json }}"
    body_format: 'json'
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: "{{ ansible_tower.verify_ssl | default('true') }}"
  when:
    - this_template.patch is defined
    - new_job_template.state == 'present'

- name: lookup the the tower credentials id "{{ this_template.tower_credential }}"
  uri:
    url: "{{ ansible_tower.url | regex_replace('\\/$','')}}/api/v2/credentials/?search={{ this_template.tower_credential }}"
    user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    password: "{{ ansible_tower.admin_password }}"
    force_basic_auth: yes
    method: GET
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: "{{ ansible_tower.verify_ssl | default('true') }}"
  register: tower_credential_lookup
  when:
    - this_template.tower_credential is defined
    - new_job_template.state == 'present'

# This is a bit horrible, 400 is not a sucess
- name: add the tower credential for template "{{ this_template.name }}"
  uri:
    url: "{{ ansible_tower.url | regex_replace('\\/$','')}}/api/v2/job_templates/{{ new_job_template.id }}/credentials/"
    user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    password: "{{ ansible_tower.admin_password }}"
    force_basic_auth: yes
    method: POST
    body: |
      { 'id': {{ tower_credential_lookup.json.results.0.id}} }
    body_format: 'json'
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: "{{ ansible_tower.verify_ssl | default('true') }}"
    status_code: [204,400]
  when:
    - this_template.tower_credential is defined
    - new_job_template.state == 'present'
    - tower_credential_lookup.json.count == 1

- name: lookup the the vault credentials id "{{ this_template.tower_credential }}"
  uri:
    url: "{{ ansible_tower.url | regex_replace('\\/$','')}}/api/v2/credentials/?search={{ this_template.vault_credential }}"
    user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    password: "{{ ansible_tower.admin_password }}"
    force_basic_auth: yes
    method: GET
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: "{{ ansible_tower.verify_ssl | default('true') }}"
  register: vault_credential_lookup
  when:
    - this_template.vault_credential is defined
    - new_job_template.state == 'present'

# This is a bit horrible, 400 is not a sucess
- name: add the vault credential for template "{{ this_template.name }}"
  uri:
    url: "{{ ansible_tower.url | regex_replace('\\/$','')}}/api/v2/job_templates/{{ new_job_template.id }}/credentials/"
    user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    password: "{{ ansible_tower.admin_password }}"
    force_basic_auth: yes
    method: POST
    body: |
      { 'id': {{ vault_credential_lookup.json.results.0.id}} }
    body_format: 'json'
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: "{{ ansible_tower.verify_ssl | default('true') }}"
    status_code: [204,400]
  when:
    - this_template.vault_credential is defined
    - new_job_template.state == 'present'
    - vault_credential_lookup.json.count == 1

