---
- name: create hosts for this inventory
  tower_host:
    name: "{{ this_host.name }}"
    description: "{{ this_host.description | default(omit) }}"
    inventory: "{{ this_inventory.1.name }}"
    state: "{{ this_host.state | default('present') }}"
    variables: "{{ this_host.variables | default({}) | to_yaml() | default(omit) }}"
    tower_host: "{{ ansible_tower.url | default(omit) }}"
    tower_username: "{{ ansible_tower.tower_username | default(omit) }}"
    tower_password: "{{ ansible_tower.tower_password | default(omit) }}"
    tower_verify_ssl: "{{ ansible_tower.verify_ssl | default('true') }}"
  loop: "{{ this_inventory.1.hosts }}"
  loop_control:
    loop_var: this_host
    label: "{{ this_inventory.0.name }} {{ this_host.name }}"
  no_log: "{{ ansible_debug_no_log | default('true') }}"
